CREATE TABLE rule (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  project CHAR(10) NOT NULL DEFAULT '' COMMENT 'project',
  group CHAR(10) NOT NULL DEFAULT '' COMMENT 'group',
  type VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'rule type',
  content VARCHAR(200) NOT NULL DEFAULT '' COLLATE utf8_bin COMMENT 'rule content',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'accept time',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'update time',
  enable TINYINT NOT NULL DEFAULT 1 COMMENT 'for delete',
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COMMENT='config center';